name: video_player_platform_interface
description: A common platform interface for the video_player plugin.
version: 6.3.0

publish_to: 'none'

environment:
  sdk: ^3.1.0
  flutter: '>=3.13.0'

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.1.7

dev_dependencies:
  flutter_test:
    sdk: flutter

topics:
  - video
  - video-player
