name: video_player
version: 2.9.0

publish_to: 'none'

environment:
  sdk: '>=3.2.3 <4.0.0'
  flutter: '>=3.16.6'

flutter:
  plugin:
    platforms:
      android:
        default_package: video_player_android
      ios:
        default_package: video_player_avfoundation
      macos:
        default_package: video_player_avfoundation
      web:
        default_package: video_player_web

dependencies:
  flutter:
    sdk: flutter
  html: ^0.15.0
  video_player_android:
    git:
      url: git@github.com:kim-company/packages.git
      path: packages/video_player/video_player_android
      ref: video-player-pip
  video_player_avfoundation:
    git:
      url: git@github.com:kim-company/packages.git
      path: packages/video_player/video_player_avfoundation
      ref: video-player-pip
  video_player_platform_interface:
    git:
      url: git@github.com:kim-company/packages.git
      path: packages/video_player/video_player_platform_interface
      ref: video-player-pip
  video_player_web:
    git:
      url: git@github.com:kim-company/packages.git
      path: packages/video_player/video_player_web
      ref: video-player-pip

dev_dependencies:
  flutter_test:
    sdk: flutter

topics:
  - video
  - video-player
