name: video_player_android
description: Android implementation of the video_player plugin.
version: 2.5.0

publish_to: 'none'

environment:
  sdk: ^3.2.0
  flutter: '>=3.16.0'

flutter:
  plugin:
    implements: video_player
    platforms:
      android:
        dartPluginClass: AndroidVideoPlayer
        package: io.flutter.plugins.videoplayer
        pluginClass: VideoPlayerPlugin

dependencies:
  flutter:
    sdk: flutter
  video_player_platform_interface:
    git:
      url: git@github.com:kim-company/packages.git
      path: packages/video_player/video_player_platform_interface
      ref: video-player-pip

dev_dependencies:
  flutter_test:
    sdk: flutter
  pigeon: ^9.2.5

topics:
  - video
  - video-player
