name: video_player_avfoundation
description: iOS and macOS implementation of the video_player plugin.
version: 2.6.0

publish_to: 'none'

environment:
  sdk: ^3.2.3
  flutter: '>=3.16.6'

flutter:
  plugin:
    implements: video_player
    platforms:
      ios:
        dartPluginClass: AVFoundationVideoPlayer
        pluginClass: FVPVideoPlayerPlugin
        sharedDarwinSource: true
      macos:
        dartPluginClass: AVFoundationVideoPlayer
        pluginClass: FVPVideoPlayerPlugin
        sharedDarwinSource: true

dependencies:
  flutter:
    sdk: flutter
  video_player_platform_interface:
    git:
      url: git@github.com:kim-company/packages.git
      path: packages/video_player/video_player_platform_interface
      ref: video-player-pip

dev_dependencies:
  flutter_test:
    sdk: flutter
  pigeon: ^18.0.0

topics:
  - video
  - video-player
