name: video_player_web
description: Web platform implementation of video_player.
version: 2.3.0

publish_to: 'none'

environment:
  sdk: ^3.3.0
  flutter: '>=3.19.0'

flutter:
  plugin:
    implements: video_player
    platforms:
      web:
        pluginClass: VideoPlayerPlugin
        fileName: video_player_web.dart

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  video_player_platform_interface:
    git:
      url: git@github.com:kim-company/packages.git
      path: packages/video_player/video_player_platform_interface
      ref: video-player-pip
  web: ^0.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter

topics:
  - video
  - video-player
